### ISSUE TITLE
软件包构建与发布

### ISSUE THREAD

**Issue by msojocs** [msojocs/wechat-web-devtools-linux#5]
## 发布平台：
- [x] [AUR](https://aur.archlinux.org/packages/wechat-devtools)
- [x] [MPR](https://mpr.makedeb.org/packages/wechat-devtools)
- [x] 星火商店（上传更新填信息很烦） [要求](https://deepin-community-store.gitee.io/spark-wiki/#/Submit/Submit?id=%e7%89%88%e6%9d%83%e8%a6%81%e6%b1%82) [投递链接（找了半天）](https://upload.deepinos.org/index) 注：更新有点麻烦，有空写个油猴脚本帮助管理
- [x] #34
- [x] UOS商店 [地址](https://store.chinauos.com/) 好家伙，之前平台在改版，我来得真不是时候
## 发布格式：
- [x] 普通打包
- [x] Appimage
- [x] deb(deprecated)
- [x] deb(using debuild)
- [x] pkg.tar.zst

## 其他：
- [ ] ia32（暂不处理，有需求再处理）
- [x] 低版本构建，加强兼容性
- [x] 规范版本命名

## TODO:
- [ ] 优化打包内容（如更新日志等）

**Comment by msojocs** [comment]
后两者构建提交过于复杂，弃用。

**Comment by msojocs** [comment]
snap有望尝试。
之前是磁盘空间不够，处理不好就不想弄; 
现在找到自定义multipass存储目录的方法了。

https://github.com/canonical/multipass/pull/1789#issuecomment-704991752

**Comment by msojocs** [comment]
目前`snap`仅能打开开发工具;
由于`wine`问题为处理，并不能正常使用;

**Comment by msojocs** [comment]
> 能不能打包成appimage 这样的话能免去安装的复杂性，也有一定的跨发行版兼容性

感谢建议，会优先进行尝试

**Comment by zhea55** [comment]
@msojocs 

ubuntu可以发布到这个地方，和aur很相似。
https://mpr.makedeb.org/

**Comment by zhea55** [comment]
```bash
/tmp/.mount_WeChatinNMMm/AppRun: line 2: /home/username/Downloads/bin/wechat-devtools: No such file or directory
```
我看appImage版本，好像还有依赖没有解决。

**Comment by msojocs** [comment]
@zhea55 
感谢反馈，依赖确实完全没有处理; 
但这个提示是找不到启动文件，应该是`appimage`构建脚本有点问题，我会再做修正。

**Comment by lanomw** [comment]
微信开发工具哪个版本的，1.05以上吗

**Comment by zhea55** [comment]
> @zhea55 感谢反馈，依赖确实完全没有处理; 但这个提示是找不到启动文件，应该是`appimage`构建脚本有点问题，我会再做修正。

太佩服楼主的命令行编码技巧了。

我用了这么多年linux，只会

sudo apt update
sudo pacman -Syu

**Comment by msojocs** [comment]
@zhea55 多用多尝试就会了；
年初的时候，我遇到滚动更新挂掉还只会重装系统解决，寒假查资料才知道命令行不挂就把更新的进度用命令行跑满，一般就能解决。
脚本也是操作系统实验课有了解一点，主要还是边查资料边解决问题学的快。

**Comment by zhea55** [comment]
> @zhea55 多用多尝试就会了； 年初的时候，我遇到滚动更新挂掉还只会重装系统解决，寒假查资料才知道命令行不挂就把更新的进度用命令行跑满，一般就能解决。 脚本也是操作系统实验课有了解一点，主要还是边查资料边解决问题学的快。

竟然还是学生。这让我有点无地自容了。

我还记得我之前鼓捣这个脚本的时候，每次都是rebuild-modules那一步报出了很多的错误。
不知道为什么你的脚本这一步非常顺利，而且感觉编译的东西很少。我记得我之前弄，那个nodegit编译非常慢。

还有spdlog这个东西一直编译失败。

我今天在猜测，有没有可能跟你一直使用root帐号有关系。我这里一直是sudo用户。

编译的时候可能没有执行权限。

**Comment by msojocs** [comment]
> > @zhea55 多用多尝试就会了； 年初的时候，我遇到滚动更新挂掉还只会重装系统解决，寒假查资料才知道命令行不挂就把更新的进度用命令行跑满，一般就能解决。 脚本也是操作系统实验课有了解一点，主要还是边查资料边解决问题学的快。
> 
> 竟然还是学生。这让我有点无地自容了。
> 
> 我还记得我之前鼓捣这个脚本的时候，每次都是rebuild-modules那一步报出了很多的错误。 不知道为什么你的脚本这一步非常顺利，而且感觉编译的东西很少。我记得我之前弄，那个nodegit编译非常慢。
> 
> 还有spdlog这个东西一直编译失败。
> 
> 我今天在猜测，有没有可能跟你一直使用root帐号有关系。我这里一直是sudo用户。
> 
> 编译的时候可能没有执行权限。

`nodegit`现在也还是很慢的;

这个跟用户无关，你可以与原始文件进行对比差异查找原因。

**Comment by maoxuner** [comment]
我之前也尝试接手这个项目的，太费精力了，也没搞定。真是长江后浪推前浪，后生可畏。加油吧小伙子

**Comment by sdlddr** [comment]
请问一下大神，中国的深度系统最新版能正常使用您的软件包吗？有没有在其软件商店中发布呢？

**Comment by msojocs** [comment]
@sdlddr 未测试，暂时没有在商店发布。

**Comment by msojocs** [comment]
snap与flatpak类似，需要在构建过程中给予网络权限

**Comment by msojocs** [comment]
snap 商店功能残缺，不再处理
